deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  structuredConfig:
    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    limits_config:
      retention_period: 168h
      reject_old_samples: false

    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      delete_request_store: filesystem

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

extraVolumes:
  - name: loki-data
    emptyDir: {}

extraVolumeMounts:
  - name: loki-data
    mountPath: /var/loki
    subPath: "" 

read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false
gateway:
  enabled: false
minio:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: false

test:
  enabled: false